apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-pv
  labels:
    app: food-ordering
    type: media-storage
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /data/food-ordering/media
    type: DirectoryOrCreate
